[[constraint]]
  name = "k8s.io/api"
  revision = "kubernetes-1.15.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "kubernetes-1.15.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "12.0.0"